### PR TITLE
Review and MainCharacterOrTeam missing fields

### PR DESCRIPTION
**Pull request by IngBertolini**
Added missing field used originally by ComicRack

### CODE REVIEW

**Comment by gotson** [comment]
Which ComicRack version did you use to find out about those fields ?

**Comment by lordwelch** [comment]
You can see it on the example comic a made here anansi-project/comicinfo#13

**Comment by gotson** [comment]
> You can see it on the example comic a made here #13

however the 2 fields in this PR are not present in #13

**Comment by lordwelch** [comment]
I was specifically referencing this comment on the PR
https://github.com/anansi-project/comicinfo/pull/13#issuecomment-1020724484

**Comment by gotson** [comment]
@IngBertolini the fields should be added to both 2.1 and 2.0 in that case, since it's from the original CR format (2.0). The indentation looks incorrect in the XML too.

The changelog should mention the fields in the 2.0 section, not in 2.1.

I don't think we can actually track whether this was present in 1.0 ?

**Comment by IngBertolini** [comment]
> Which ComicRack version did you use to find out about those fields ?

The last version available i think (v0.9.178). I just edit all the metadata of a book and looked at the exported xml. As you can see in this screenshot, they are also present in GUI.

image

**Comment by IngBertolini** [comment]
> @IngBertolini the fields should be added to both 2.1 and 2.0 in that case, since it's from the original CR format (2.0). The indentation looks incorrect in the XML too.
> 
> The changelog should mention the fields in the 2.0 section, not in 2.1.
> 
> I don't think we can actually track whether this was present in 1.0 ?

Sure, i can fix that. But what about the field Day? It's prensent in v2.0 but in the changelog it appears under v2.1

**Comment by gotson** [comment]
> > @IngBertolini the fields should be added to both 2.1 and 2.0 in that case, since it's from the original CR format (2.0). The indentation looks incorrect in the XML too.
> > The changelog should mention the fields in the 2.0 section, not in 2.1.
> > I don't think we can actually track whether this was present in 1.0 ?
> 
> Sure, i can fix that. But what about the field Day? It's prensent in v2.0 but in the changelog it appears under v2.1

At first we thought the schema was official, while in fact it was inferred from the actual XML.

The schema that was going around before we started this initiative did not mention `Day`, while the XML had it. We could probably remove `Day` from the 2.1 changelog.

**Comment by IngBertolini** [comment]
Done, i added the field also to version 2.0 and updated the changelog.

**Comment by gotson** [comment]
Seems like there are some conflicts in your PR, can you help to resolve it?

**Comment by IngBertolini** [comment]
Done!

**Review by gotson — APPROVED** [review]
LGTM

**Pull request merged**
