### PR TITLE
Correct v2.0

### PR DESCRIPTION
**Pull request by lordwelch**
Add Day, CommunityRating, Bookmark

These are all observed from version 0.9.178 of ComicRack:

https://web.archive.org/web/20180926062727/http://comicrack.cyolito.com/downloads

### CODE REVIEW

**Comment by gotson** [comment]
Did you get this by decompiling ? The `CommunityRating` doesn't seem to appear [here](https://github.com/anansi-project/comicinfo/issues/11#issuecomment-1018825727) though.

**Comment by lordwelch** [comment]
No, just set every option I could and exported a comic

**Comment by gotson** [comment]
@SenorSmartyPants is that something we can confirm from decompiling?

**Comment by SenorSmartyPants** [comment]
> @SenorSmartyPants is that something we can confirm from decompiling?

At the moment I can't find it via decompiling. What I can confirm is that all those properties are written to comicinfo.xml in some of my files as well. But if you select an issue with communityRating set in CRW and do "copy data" ctrl-C, and paste that into notepad. The result will not include communityRating, even thou it is in the file written out into the CBZ. So I think I found the routine for copy data which must not be what is called when exporting/updating comicinfo.xml.

**Comment by gotson** [comment]
> Add Day, CommunityRating, Bookmark
> 
> These are all observed from version 0.9.178 of ComicRack:
> 
> https://web.archive.org/web/20180926062727/http://comicrack.cyolito.com/downloads

If my understanding is correct, community rating is to rate the book, like 0 to 5 stars or something like that? What about Bookmark, what does it do or how is it used in CR?

**Comment by lordwelch** [comment]
Here is the file that I exported in CR [Doctorow, Cory - Craphound.CR.zip](https://github.com/anansi-project/comicinfo/files/7929980/Doctorow.Cory.-.Craphound.CR.zip) it does allow you to create a bookmark on whichever page you are viewing but you have to name your bookmark which is more how like chapters work, and I think that that is what the intended use was.

I also updated the community rating it only has one decimal place, in ComicRack it has 5 stars that you can click on, depending on where you click will set the rating accurate to .1

**Comment by lordwelch** [comment]
The CR manual on Bookmarks https://web.archive.org/web/20220602205424/https://sites.google.com/site/comicrackmanual/chapter-05-reader/reader-context-menu

Feature request on Ubooquity https://ubooquity.userecho.com/en/communities/1/topics/688-feature-request-comicrack-bookmark-api
sumatra pdf reader has an open issue for adding bookmark support sumatrapdfreader/sumatrapdf#1201

KCC (Kindle Comic Converter) who seems to have noticed the Bookmark attribute first as most places link back to it https://github.com/ciromattia/kcc/wiki/ComicRack-metadata

Kuboo supports this before they archived their project jnp1500/Kuboo#25

[peruse](https://phabricator.kde.org/source/peruse/repository/master/) which was active until 2020 implements bookmarks https://phabricator.kde.org/D15601

**Comment by majora2007** [comment]
Interesting that bookmarks are basically a way to save progress.

**Review by gotson — APPROVED** [review]
Looks good to me

**Comment by ajslater** [comment]
lgtm as well.
Some tags I was unaware of here for ComicInfo format. Perhaps I've been parsing v1.0

**Review by majora2007 — APPROVED** [review]
LGTM

**Pull request merged**
